// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdeBf-A9ava6H6pyzUaSf6YmDe133INg8',
    appId: '1:414858562106:web:31694e53367f8c56540303',
    messagingSenderId: '414858562106',
    projectId: 'goal-quester',
    authDomain: 'goal-quester.firebaseapp.com',
    storageBucket: 'goal-quester.appspot.com',
    measurementId: 'G-TX328P85MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYGBK7OkR8Hc_L-0cVfeEnr6AGLsgYGMk',
    appId: '1:414858562106:android:55f332429f802248540303',
    messagingSenderId: '414858562106',
    projectId: 'goal-quester',
    storageBucket: 'goal-quester.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs7WvDZHxXn89Ch3j6V7O_xNbEiIY4Dqc',
    appId: '1:414858562106:ios:a209a705bbac6070540303',
    messagingSenderId: '414858562106',
    projectId: 'goal-quester',
    storageBucket: 'goal-quester.appspot.com',
    iosBundleId: 'com.example.goalQuester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs7WvDZHxXn89Ch3j6V7O_xNbEiIY4Dqc',
    appId: '1:414858562106:ios:7b81757d066a266d540303',
    messagingSenderId: '414858562106',
    projectId: 'goal-quester',
    storageBucket: 'goal-quester.appspot.com',
    iosBundleId: 'com.example.goalQuester.RunnerTests',
  );
}
