// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVsBPFP3IcxbYHhXg1CJOBFq3j3WDrkYc',
    appId: '1:1065294549255:web:148df171e50c1ca798f5a2',
    messagingSenderId: '1065294549255',
    projectId: 'goal-questar',
    authDomain: 'goal-questar.firebaseapp.com',
    storageBucket: 'goal-questar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp8J0GrsCR40bQP3_tNaQVZDkncJrtK7U',
    appId: '1:1065294549255:android:12272e516ac4814d98f5a2',
    messagingSenderId: '1065294549255',
    projectId: 'goal-questar',
    storageBucket: 'goal-questar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhVp6YRX1UzeAO8UyEyhv-AHgGWvadYak',
    appId: '1:1065294549255:ios:63173dda17004e3c98f5a2',
    messagingSenderId: '1065294549255',
    projectId: 'goal-questar',
    storageBucket: 'goal-questar.appspot.com',
    iosBundleId: 'com.example.goalQuester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhVp6YRX1UzeAO8UyEyhv-AHgGWvadYak',
    appId: '1:1065294549255:ios:04b3e37e8d43c0f098f5a2',
    messagingSenderId: '1065294549255',
    projectId: 'goal-questar',
    storageBucket: 'goal-questar.appspot.com',
    iosBundleId: 'com.example.goalQuester.RunnerTests',
  );
}
